services:
  dozzle:
    image: amir20/dozzle:${DOZZLE_TAG}
    container_name: dozzle
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "${DOZZLE_PORT}:8080"
    security_opt:
      - no-new-privileges:true
    environment:
      DOZZLE_LEVEL: info
    networks:
      - shared_net

networks:
  shared_net:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_shared_net
