services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:${AZURITE_TAG}
    container_name: azurite
    extends:
      file: ../../policies/base.yml
      service: default-policy
    ports:
      - "${AZURITE_BLOB_PORT}:10000"
      - "${AZURITE_QUEUE_PORT}:10001"
      - "${AZURITE_TABLE_PORT}:10002"
    command: "azurite --skipApiVersionCheck --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0"
    volumes:
      - ./volumes/data:/data
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "10000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - shared_net

networks:
  shared_net:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_shared_net