services:
  rabbitmq:
    image: rabbitmq:${RABBITMQ_TAG}
    container_name: rabbitmq
    extends:
      file: ../../policies/base.yml
      service: default-policy
    networks:
      - shared_net
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MGMT_PORT}:15672"
    volumes:
      - ./volumes/data:/var/lib/rabbitmq
      - ./volumes/config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  shared_net:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_shared_net
